FROM {{base_image}}

RUN apk --no-cache upgrade \
    && apk add --no-cache curl git

WORKDIR /var/lib/nginx

RUN rm -rf html \
    && git clone --depth=1 https://github.com/sugarlabs/musicblocks.git \
    && mv -f musicblocks html

EXPOSE 80 443 3000

CMD ["nginx", "-g", "daemon off;"]

